import Link from "next/link";
import { redirect } from "next/navigation";
import {
  Activity,
  ArrowLeft,
  BarChart3,
  LineChart as LineChartIcon,
  ShieldAlert,
  TrendingDown,
  TrendingUp,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import EquityChart from "@/components/EquityChart";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import {
  formatCurrencyByLanguage,
  formatDateByLanguage,
  formatPercentByLanguage,
  normalizeAppLanguage,
  type AppLanguage,
} from "@/lib/i18n";

type StatCardProps = {
  label: string;
  value: string | number;
  description: string;
  icon: LucideIcon;
  tone?: string;
};

type EquityLabels = {
  heroBadge: string;
  heroEyebrow: string;
  heroTitle: string;
  heroDescription: string;
  backToAccountHub: string;

  currentEquity: string;
  currentEquityDescription: string;
  totalPnl: string;
  totalPnlDescription: string;
  growth: string;
  growthDescription: string;
  maxDrawdown: string;
  maxDrawdownDescription: string;

  accountGrowth: string;
  equityProgression: string;
  noTradesChart: string;

  equityPeak: string;
  equityPeakDescription: string;
  lowestEquity: string;
  lowestEquityDescription: string;

  positiveTrades: string;
  positiveTradesDescription: string;
  negativeTrades: string;
  negativeTradesDescription: string;
  flatTrades: string;
  flatTradesDescription: string;
  averagePnl: string;
  averagePnlDescription: string;

  bestTrade: string;
  bestTradeDescription: string;
  worstTrade: string;
  worstTradeDescription: string;

  equityHistory: string;
  tradeByTradeProgression: string;
  showingLatest: (shown: number, total: number) => string;

  unknownSymbol: string;
  equity: string;
  drawdown: string;
  date: string;
  symbol: string;
  outcome: string;
  pnl: string;
  noEquityHistory: string;
};

const equityLabels: Record<AppLanguage, EquityLabels> = {
  it: {
    heroBadge: "Tracciamento capitale",
    heroEyebrow: "Centro controllo equity",
    heroTitle: "Curva Equity",
    heroDescription:
      "Segui la crescita dellÃ¢â‚¬â„¢account, la protezione del capitale, il comportamento del drawdown e lÃ¢â‚¬â„¢evoluzione della tua equity nel tempo.",
    backToAccountHub: "Torna allÃ¢â‚¬â„¢Account Hub",

    currentEquity: "Equity attuale",
    currentEquityDescription:
      "Ultima equity calcolata dopo i trade chiusi.",
    totalPnl: "PnL totale",
    totalPnlDescription:
      "Profitto o perdita totale generata dallÃ¢â‚¬â„¢account.",
    growth: "Crescita",
    growthDescription:
      "Performance rispetto al saldo iniziale.",
    maxDrawdown: "Drawdown massimo",
    maxDrawdownDescription:
      "Peggiore calo dellÃ¢â‚¬â„¢equity registrato sullÃ¢â‚¬â„¢account.",

    accountGrowth: "Crescita account",
    equityProgression: "Progressione Equity",
    noTradesChart:
      "Nessun trade presente. Quando aggiungerai operazioni, la curva equity comparirÃƒÂ  qui.",

    equityPeak: "Picco Equity",
    equityPeakDescription:
      "Valore equity piÃƒÂ¹ alto registrato su questo account.",
    lowestEquity: "Equity minima",
    lowestEquityDescription:
      "Valore equity piÃƒÂ¹ basso registrato includendo il saldo iniziale.",

    positiveTrades: "Trade positivi",
    positiveTradesDescription:
      "Trade chiusi con risultato positivo.",
    negativeTrades: "Trade negativi",
    negativeTradesDescription:
      "Trade chiusi con risultato negativo.",
    flatTrades: "Trade flat",
    flatTradesDescription:
      "Trade chiusi a break-even o senza PnL.",
    averagePnl: "PnL medio",
    averagePnlDescription:
      "Risultato medio per trade registrato.",

    bestTrade: "Miglior trade",
    bestTradeDescription:
      "Risultato positivo singolo piÃƒÂ¹ grande registrato su questo account.",
    worstTrade: "Peggior trade",
    worstTradeDescription:
      "Risultato negativo singolo piÃƒÂ¹ grande registrato su questo account.",

    equityHistory: "Storico equity",
    tradeByTradeProgression: "Progressione trade per trade",
    showingLatest: (shown, total) =>
      `Mostrati gli ultimi ${shown} di ${total} trade`,

    unknownSymbol: "Simbolo sconosciuto",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Data",
    symbol: "Simbolo",
    outcome: "Esito",
    pnl: "PnL",
    noEquityHistory:
      "Nessuno storico equity presente. Aggiungi trade per iniziare a tracciare la progressione del capitale.",
  },

  en: {
    heroBadge: "Capital tracking",
    heroEyebrow: "Equity control center",
    heroTitle: "Equity Curve",
    heroDescription:
      "Follow account growth, capital protection, drawdown behavior and the progression of your trading equity over time.",
    backToAccountHub: "Back to Account Hub",

    currentEquity: "Current Equity",
    currentEquityDescription:
      "Latest calculated account equity after closed trades.",
    totalPnl: "Total PnL",
    totalPnlDescription:
      "Total profit or loss generated by the account.",
    growth: "Growth",
    growthDescription:
      "Performance compared to the initial balance.",
    maxDrawdown: "Max Drawdown",
    maxDrawdownDescription:
      "Deepest equity pullback recorded on the account.",

    accountGrowth: "Account growth",
    equityProgression: "Equity Progression",
    noTradesChart:
      "No trades yet. Once trades are added, the equity curve will appear here.",

    equityPeak: "Equity Peak",
    equityPeakDescription:
      "Highest recorded equity value for this account.",
    lowestEquity: "Lowest Equity",
    lowestEquityDescription:
      "Lowest recorded equity value including the initial balance.",

    positiveTrades: "Positive Trades",
    positiveTradesDescription:
      "Trades closed with a positive result.",
    negativeTrades: "Negative Trades",
    negativeTradesDescription:
      "Trades closed with a negative result.",
    flatTrades: "Flat Trades",
    flatTradesDescription:
      "Trades closed at break-even or without PnL.",
    averagePnl: "Average PnL",
    averagePnlDescription:
      "Average result per recorded trade.",

    bestTrade: "Best Trade",
    bestTradeDescription:
      "Largest single positive result recorded on this account.",
    worstTrade: "Worst Trade",
    worstTradeDescription:
      "Largest single negative result recorded on this account.",

    equityHistory: "Equity history",
    tradeByTradeProgression: "Trade by Trade Progression",
    showingLatest: (shown, total) =>
      `Showing latest ${shown} of ${total} trades`,

    unknownSymbol: "Unknown Symbol",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Date",
    symbol: "Symbol",
    outcome: "Outcome",
    pnl: "PnL",
    noEquityHistory:
      "No equity history yet. Add trades to start tracking capital progression.",
  },

  uk: {
    heroBadge: "Ãâ€™Ã‘â€“ÃÂ´Ã‘ÂÃ‘â€šÃÂµÃÂ¶ÃÂµÃÂ½ÃÂ½Ã‘Â ÃÂºÃÂ°ÃÂ¿Ã‘â€“Ã‘â€šÃÂ°ÃÂ»Ã‘Æ’",
    heroEyebrow: "ÃÂ¦ÃÂµÃÂ½Ã‘â€šÃ‘â‚¬ ÃÂºÃÂ¾ÃÂ½Ã‘â€šÃ‘â‚¬ÃÂ¾ÃÂ»Ã‘Å½ equity",
    heroTitle: "ÃÅ¡Ã‘â‚¬ÃÂ¸ÃÂ²ÃÂ° Equity",
    heroDescription:
      "Ãâ€™Ã‘â€“ÃÂ´Ã‘ÂÃ‘â€šÃÂµÃÂ¶Ã‘Æ’ÃÂ¹ ÃÂ·Ã‘â‚¬ÃÂ¾Ã‘ÂÃ‘â€šÃÂ°ÃÂ½ÃÂ½Ã‘Â ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂ°, ÃÂ·ÃÂ°Ã‘â€¦ÃÂ¸Ã‘ÂÃ‘â€š ÃÂºÃÂ°ÃÂ¿Ã‘â€“Ã‘â€šÃÂ°ÃÂ»Ã‘Æ’, ÃÂ¿ÃÂ¾ÃÂ²ÃÂµÃÂ´Ã‘â€“ÃÂ½ÃÂºÃ‘Æ’ drawdown Ã‘â€šÃÂ° Ã‘â‚¬ÃÂ¾ÃÂ·ÃÂ²ÃÂ¸Ã‘â€šÃÂ¾ÃÂº Ã‘â€šÃÂ¾Ã‘â‚¬ÃÂ³ÃÂ¾ÃÂ²ÃÂ¾Ã‘â€” equity ÃÂ· Ã‘â€¡ÃÂ°Ã‘ÂÃÂ¾ÃÂ¼.",
    backToAccountHub: "ÃÂÃÂ°ÃÂ·ÃÂ°ÃÂ´ ÃÂ´ÃÂ¾ Account Hub",

    currentEquity: "ÃÅ¸ÃÂ¾Ã‘â€šÃÂ¾Ã‘â€¡ÃÂ½ÃÂ° equity",
    currentEquityDescription:
      "ÃÅ¾Ã‘ÂÃ‘â€šÃÂ°ÃÂ½ÃÂ½Ã‘â€ Ã‘â‚¬ÃÂ¾ÃÂ·Ã‘â‚¬ÃÂ°Ã‘â€¦ÃÂ¾ÃÂ²ÃÂ°ÃÂ½ÃÂµ ÃÂ·ÃÂ½ÃÂ°Ã‘â€¡ÃÂµÃÂ½ÃÂ½Ã‘Â equity ÃÂ¿Ã‘â€“Ã‘ÂÃÂ»Ã‘Â ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬ÃÂ¸Ã‘â€šÃÂ¸Ã‘â€¦ Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´.",
    totalPnl: "Ãâ€”ÃÂ°ÃÂ³ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ¸ÃÂ¹ PnL",
    totalPnlDescription:
      "Ãâ€”ÃÂ°ÃÂ³ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ¸ÃÂ¹ ÃÂ¿Ã‘â‚¬ÃÂ¸ÃÂ±Ã‘Æ’Ã‘â€šÃÂ¾ÃÂº ÃÂ°ÃÂ±ÃÂ¾ ÃÂ·ÃÂ±ÃÂ¸Ã‘â€šÃÂ¾ÃÂº, Ã‘ÂÃ‘â€šÃÂ²ÃÂ¾Ã‘â‚¬ÃÂµÃÂ½ÃÂ¸ÃÂ¹ ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂ¾ÃÂ¼.",
    growth: "Ãâ€”Ã‘â‚¬ÃÂ¾Ã‘ÂÃ‘â€šÃÂ°ÃÂ½ÃÂ½Ã‘Â",
    growthDescription:
      "ÃÂ ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ²Ã‘â€“ÃÂ´ÃÂ½ÃÂ¾Ã‘ÂÃÂ½ÃÂ¾ ÃÂ¿ÃÂ¾Ã‘â€¡ÃÂ°Ã‘â€šÃÂºÃÂ¾ÃÂ²ÃÂ¾ÃÂ³ÃÂ¾ ÃÂ±ÃÂ°ÃÂ»ÃÂ°ÃÂ½Ã‘ÂÃ‘Æ’.",
    maxDrawdown: "ÃÅ“ÃÂ°ÃÂºÃ‘ÂÃÂ¸ÃÂ¼ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ¸ÃÂ¹ drawdown",
    maxDrawdownDescription:
      "ÃÂÃÂ°ÃÂ¹ÃÂ³ÃÂ»ÃÂ¸ÃÂ±Ã‘Ë†ÃÂµ ÃÂ¿Ã‘â‚¬ÃÂ¾Ã‘ÂÃ‘â€“ÃÂ´ÃÂ°ÃÂ½ÃÂ½Ã‘Â equity, ÃÂ·ÃÂ°Ã‘â€žÃ‘â€“ÃÂºÃ‘ÂÃÂ¾ÃÂ²ÃÂ°ÃÂ½ÃÂµ ÃÂ½ÃÂ° ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃ‘â€“.",

    accountGrowth: "Ãâ€”Ã‘â‚¬ÃÂ¾Ã‘ÂÃ‘â€šÃÂ°ÃÂ½ÃÂ½Ã‘Â ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂ°",
    equityProgression: "ÃÅ¸Ã‘â‚¬ÃÂ¾ÃÂ³Ã‘â‚¬ÃÂµÃ‘ÂÃ‘â€“Ã‘Â Equity",
    noTradesChart:
      "ÃÂ£ÃÂ³ÃÂ¾ÃÂ´ Ã‘â€°ÃÂµ ÃÂ½ÃÂµÃÂ¼ÃÂ°Ã‘â€. ÃÅ¡ÃÂ¾ÃÂ»ÃÂ¸ Ã‘â€šÃÂ¸ ÃÂ´ÃÂ¾ÃÂ´ÃÂ°Ã‘ÂÃÂ¸ Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸, ÃÂºÃ‘â‚¬ÃÂ¸ÃÂ²ÃÂ° equity ÃÂ·Ã¢â‚¬â„¢Ã‘ÂÃÂ²ÃÂ¸Ã‘â€šÃ‘Å’Ã‘ÂÃ‘Â Ã‘â€šÃ‘Æ’Ã‘â€š.",

    equityPeak: "ÃÅ¸Ã‘â€“ÃÂº Equity",
    equityPeakDescription:
      "ÃÂÃÂ°ÃÂ¹ÃÂ²ÃÂ¸Ã‘â€°ÃÂµ ÃÂ·ÃÂ½ÃÂ°Ã‘â€¡ÃÂµÃÂ½ÃÂ½Ã‘Â equity, ÃÂ·ÃÂ°Ã‘â€žÃ‘â€“ÃÂºÃ‘ÂÃÂ¾ÃÂ²ÃÂ°ÃÂ½ÃÂµ ÃÂ½ÃÂ° Ã‘â€ Ã‘Å’ÃÂ¾ÃÂ¼Ã‘Æ’ ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃ‘â€“.",
    lowestEquity: "ÃÅ“Ã‘â€“ÃÂ½Ã‘â€“ÃÂ¼ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ° equity",
    lowestEquityDescription:
      "ÃÂÃÂ°ÃÂ¹ÃÂ½ÃÂ¸ÃÂ¶Ã‘â€¡ÃÂµ ÃÂ·ÃÂ½ÃÂ°Ã‘â€¡ÃÂµÃÂ½ÃÂ½Ã‘Â equity ÃÂ· Ã‘Æ’Ã‘â‚¬ÃÂ°Ã‘â€¦Ã‘Æ’ÃÂ²ÃÂ°ÃÂ½ÃÂ½Ã‘ÂÃÂ¼ ÃÂ¿ÃÂ¾Ã‘â€¡ÃÂ°Ã‘â€šÃÂºÃÂ¾ÃÂ²ÃÂ¾ÃÂ³ÃÂ¾ ÃÂ±ÃÂ°ÃÂ»ÃÂ°ÃÂ½Ã‘ÂÃ‘Æ’.",

    positiveTrades: "ÃÅ¸ÃÂ¾ÃÂ·ÃÂ¸Ã‘â€šÃÂ¸ÃÂ²ÃÂ½Ã‘â€“ Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸",
    positiveTradesDescription:
      "ÃÂ£ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸, ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬ÃÂ¸Ã‘â€šÃ‘â€“ ÃÂ· ÃÂ¿ÃÂ¾ÃÂ·ÃÂ¸Ã‘â€šÃÂ¸ÃÂ²ÃÂ½ÃÂ¸ÃÂ¼ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€šÃÂ¾ÃÂ¼.",
    negativeTrades: "ÃÂÃÂµÃÂ³ÃÂ°Ã‘â€šÃÂ¸ÃÂ²ÃÂ½Ã‘â€“ Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸",
    negativeTradesDescription:
      "ÃÂ£ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸, ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬ÃÂ¸Ã‘â€šÃ‘â€“ ÃÂ· ÃÂ½ÃÂµÃÂ³ÃÂ°Ã‘â€šÃÂ¸ÃÂ²ÃÂ½ÃÂ¸ÃÂ¼ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€šÃÂ¾ÃÂ¼.",
    flatTrades: "Flat Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸",
    flatTradesDescription:
      "ÃÂ£ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸, ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬ÃÂ¸Ã‘â€šÃ‘â€“ ÃÂ² break-even ÃÂ°ÃÂ±ÃÂ¾ ÃÂ±ÃÂµÃÂ· PnL.",
    averagePnl: "ÃÂ¡ÃÂµÃ‘â‚¬ÃÂµÃÂ´ÃÂ½Ã‘â€“ÃÂ¹ PnL",
    averagePnlDescription:
      "ÃÂ¡ÃÂµÃ‘â‚¬ÃÂµÃÂ´ÃÂ½Ã‘â€“ÃÂ¹ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ·ÃÂ° ÃÂ¾ÃÂ´ÃÂ½Ã‘Æ’ ÃÂ·ÃÂ°ÃÂ¿ÃÂ¸Ã‘ÂÃÂ°ÃÂ½Ã‘Æ’ Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´Ã‘Æ’.",

    bestTrade: "ÃÂÃÂ°ÃÂ¹ÃÂºÃ‘â‚¬ÃÂ°Ã‘â€°ÃÂ° Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ°",
    bestTradeDescription:
      "ÃÂÃÂ°ÃÂ¹ÃÂ±Ã‘â€“ÃÂ»Ã‘Å’Ã‘Ë†ÃÂ¸ÃÂ¹ ÃÂ¾ÃÂ´ÃÂ¸ÃÂ½ÃÂ¸Ã‘â€¡ÃÂ½ÃÂ¸ÃÂ¹ ÃÂ¿ÃÂ¾ÃÂ·ÃÂ¸Ã‘â€šÃÂ¸ÃÂ²ÃÂ½ÃÂ¸ÃÂ¹ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ½ÃÂ° Ã‘â€ Ã‘Å’ÃÂ¾ÃÂ¼Ã‘Æ’ ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃ‘â€“.",
    worstTrade: "ÃÂÃÂ°ÃÂ¹ÃÂ³Ã‘â€“Ã‘â‚¬Ã‘Ë†ÃÂ° Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ°",
    worstTradeDescription:
      "ÃÂÃÂ°ÃÂ¹ÃÂ±Ã‘â€“ÃÂ»Ã‘Å’Ã‘Ë†ÃÂ¸ÃÂ¹ ÃÂ¾ÃÂ´ÃÂ¸ÃÂ½ÃÂ¸Ã‘â€¡ÃÂ½ÃÂ¸ÃÂ¹ ÃÂ½ÃÂµÃÂ³ÃÂ°Ã‘â€šÃÂ¸ÃÂ²ÃÂ½ÃÂ¸ÃÂ¹ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ½ÃÂ° Ã‘â€ Ã‘Å’ÃÂ¾ÃÂ¼Ã‘Æ’ ÃÂ°ÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃ‘â€“.",

    equityHistory: "Ãâ€ Ã‘ÂÃ‘â€šÃÂ¾Ã‘â‚¬Ã‘â€“Ã‘Â equity",
    tradeByTradeProgression: "ÃÅ¸Ã‘â‚¬ÃÂ¾ÃÂ³Ã‘â‚¬ÃÂµÃ‘ÂÃ‘â€“Ã‘Â Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ° ÃÂ·ÃÂ° Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ¾Ã‘Å½",
    showingLatest: (shown, total) =>
      `ÃÅ¸ÃÂ¾ÃÂºÃÂ°ÃÂ·ÃÂ°ÃÂ½ÃÂ¾ ÃÂ¾Ã‘ÂÃ‘â€šÃÂ°ÃÂ½ÃÂ½Ã‘â€“ ${shown} ÃÂ· ${total} Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´`,

    unknownSymbol: "ÃÂÃÂµÃÂ²Ã‘â€“ÃÂ´ÃÂ¾ÃÂ¼ÃÂ¸ÃÂ¹ Ã‘ÂÃÂ¸ÃÂ¼ÃÂ²ÃÂ¾ÃÂ»",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Ãâ€ÃÂ°Ã‘â€šÃÂ°",
    symbol: "ÃÂ¡ÃÂ¸ÃÂ¼ÃÂ²ÃÂ¾ÃÂ»",
    outcome: "ÃÂ ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š",
    pnl: "PnL",
    noEquityHistory:
      "Ãâ€ Ã‘ÂÃ‘â€šÃÂ¾Ã‘â‚¬Ã‘â€“Ã‘â€” equity Ã‘â€°ÃÂµ ÃÂ½ÃÂµÃÂ¼ÃÂ°Ã‘â€. Ãâ€ÃÂ¾ÃÂ´ÃÂ°ÃÂ¹ Ã‘Æ’ÃÂ³ÃÂ¾ÃÂ´ÃÂ¸, Ã‘â€°ÃÂ¾ÃÂ± ÃÂ¿ÃÂ¾Ã‘â€¡ÃÂ°Ã‘â€šÃÂ¸ ÃÂ²Ã‘â€“ÃÂ´Ã‘ÂÃ‘â€šÃÂµÃÂ¶Ã‘Æ’ÃÂ²ÃÂ°Ã‘â€šÃÂ¸ ÃÂ¿Ã‘â‚¬ÃÂ¾ÃÂ³Ã‘â‚¬ÃÂµÃ‘Â ÃÂºÃÂ°ÃÂ¿Ã‘â€“Ã‘â€šÃÂ°ÃÂ»Ã‘Æ’.",
  },

  ru: {
    heroBadge: "ÃÅ¾Ã‘â€šÃ‘ÂÃÂ»ÃÂµÃÂ¶ÃÂ¸ÃÂ²ÃÂ°ÃÂ½ÃÂ¸ÃÂµ ÃÂºÃÂ°ÃÂ¿ÃÂ¸Ã‘â€šÃÂ°ÃÂ»ÃÂ°",
    heroEyebrow: "ÃÂ¦ÃÂµÃÂ½Ã‘â€šÃ‘â‚¬ ÃÂºÃÂ¾ÃÂ½Ã‘â€šÃ‘â‚¬ÃÂ¾ÃÂ»Ã‘Â equity",
    heroTitle: "ÃÅ¡Ã‘â‚¬ÃÂ¸ÃÂ²ÃÂ°Ã‘Â Equity",
    heroDescription:
      "ÃÂ¡ÃÂ»ÃÂµÃÂ´ÃÂ¸ ÃÂ·ÃÂ° Ã‘â‚¬ÃÂ¾Ã‘ÂÃ‘â€šÃÂ¾ÃÂ¼ ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂ°, ÃÂ·ÃÂ°Ã‘â€°ÃÂ¸Ã‘â€šÃÂ¾ÃÂ¹ ÃÂºÃÂ°ÃÂ¿ÃÂ¸Ã‘â€šÃÂ°ÃÂ»ÃÂ°, ÃÂ¿ÃÂ¾ÃÂ²ÃÂµÃÂ´ÃÂµÃÂ½ÃÂ¸ÃÂµÃÂ¼ drawdown ÃÂ¸ Ã‘â‚¬ÃÂ°ÃÂ·ÃÂ²ÃÂ¸Ã‘â€šÃÂ¸ÃÂµÃÂ¼ Ã‘â€šÃÂ¾Ã‘â‚¬ÃÂ³ÃÂ¾ÃÂ²ÃÂ¾ÃÂ¹ equity ÃÂ²ÃÂ¾ ÃÂ²Ã‘â‚¬ÃÂµÃÂ¼ÃÂµÃÂ½ÃÂ¸.",
    backToAccountHub: "ÃÂÃÂ°ÃÂ·ÃÂ°ÃÂ´ ÃÂº Account Hub",

    currentEquity: "ÃÂ¢ÃÂµÃÂºÃ‘Æ’Ã‘â€°ÃÂ°Ã‘Â equity",
    currentEquityDescription:
      "ÃÅ¸ÃÂ¾Ã‘ÂÃÂ»ÃÂµÃÂ´ÃÂ½ÃÂµÃÂµ Ã‘â‚¬ÃÂ°Ã‘ÂÃ‘ÂÃ‘â€¡ÃÂ¸Ã‘â€šÃÂ°ÃÂ½ÃÂ½ÃÂ¾ÃÂµ ÃÂ·ÃÂ½ÃÂ°Ã‘â€¡ÃÂµÃÂ½ÃÂ¸ÃÂµ equity ÃÂ¿ÃÂ¾Ã‘ÂÃÂ»ÃÂµ ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬Ã‘â€¹Ã‘â€šÃ‘â€¹Ã‘â€¦ Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂ¾ÃÂº.",
    totalPnl: "ÃÅ¾ÃÂ±Ã‘â€°ÃÂ¸ÃÂ¹ PnL",
    totalPnlDescription:
      "ÃÅ¾ÃÂ±Ã‘â€°ÃÂ°Ã‘Â ÃÂ¿Ã‘â‚¬ÃÂ¸ÃÂ±Ã‘â€¹ÃÂ»Ã‘Å’ ÃÂ¸ÃÂ»ÃÂ¸ Ã‘Æ’ÃÂ±Ã‘â€¹Ã‘â€šÃÂ¾ÃÂº, Ã‘ÂÃÂ¾ÃÂ·ÃÂ´ÃÂ°ÃÂ½ÃÂ½Ã‘â€¹ÃÂµ ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂ¾ÃÂ¼.",
    growth: "ÃÂ ÃÂ¾Ã‘ÂÃ‘â€š",
    growthDescription:
      "ÃÂ ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ¾Ã‘â€šÃÂ½ÃÂ¾Ã‘ÂÃÂ¸Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½ÃÂ¾ ÃÂ½ÃÂ°Ã‘â€¡ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ¾ÃÂ³ÃÂ¾ ÃÂ±ÃÂ°ÃÂ»ÃÂ°ÃÂ½Ã‘ÂÃÂ°.",
    maxDrawdown: "ÃÅ“ÃÂ°ÃÂºÃ‘ÂÃÂ¸ÃÂ¼ÃÂ°ÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂ¹ drawdown",
    maxDrawdownDescription:
      "ÃÂ¡ÃÂ°ÃÂ¼ÃÂ¾ÃÂµ ÃÂ³ÃÂ»Ã‘Æ’ÃÂ±ÃÂ¾ÃÂºÃÂ¾ÃÂµ Ã‘ÂÃÂ½ÃÂ¸ÃÂ¶ÃÂµÃÂ½ÃÂ¸ÃÂµ equity, ÃÂ·ÃÂ°Ã‘â€žÃÂ¸ÃÂºÃ‘ÂÃÂ¸Ã‘â‚¬ÃÂ¾ÃÂ²ÃÂ°ÃÂ½ÃÂ½ÃÂ¾ÃÂµ ÃÂ½ÃÂ° ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂµ.",

    accountGrowth: "ÃÂ ÃÂ¾Ã‘ÂÃ‘â€š ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂ°",
    equityProgression: "ÃÅ¸Ã‘â‚¬ÃÂ¾ÃÂ³Ã‘â‚¬ÃÂµÃ‘ÂÃ‘ÂÃÂ¸Ã‘Â Equity",
    noTradesChart:
      "ÃÂ¡ÃÂ´ÃÂµÃÂ»ÃÂ¾ÃÂº ÃÂ¿ÃÂ¾ÃÂºÃÂ° ÃÂ½ÃÂµÃ‘â€š. ÃÅ¡ÃÂ¾ÃÂ³ÃÂ´ÃÂ° Ã‘â€šÃ‘â€¹ ÃÂ´ÃÂ¾ÃÂ±ÃÂ°ÃÂ²ÃÂ¸Ã‘Ë†Ã‘Å’ Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸, ÃÂºÃ‘â‚¬ÃÂ¸ÃÂ²ÃÂ°Ã‘Â equity ÃÂ¿ÃÂ¾Ã‘ÂÃÂ²ÃÂ¸Ã‘â€šÃ‘ÂÃ‘Â ÃÂ·ÃÂ´ÃÂµÃ‘ÂÃ‘Å’.",

    equityPeak: "ÃÅ¸ÃÂ¸ÃÂº Equity",
    equityPeakDescription:
      "ÃÂ¡ÃÂ°ÃÂ¼ÃÂ¾ÃÂµ ÃÂ²Ã‘â€¹Ã‘ÂÃÂ¾ÃÂºÃÂ¾ÃÂµ ÃÂ·ÃÂ½ÃÂ°Ã‘â€¡ÃÂµÃÂ½ÃÂ¸ÃÂµ equity, ÃÂ·ÃÂ°Ã‘â€žÃÂ¸ÃÂºÃ‘ÂÃÂ¸Ã‘â‚¬ÃÂ¾ÃÂ²ÃÂ°ÃÂ½ÃÂ½ÃÂ¾ÃÂµ ÃÂ½ÃÂ° Ã‘ÂÃ‘â€šÃÂ¾ÃÂ¼ ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂµ.",
    lowestEquity: "ÃÅ“ÃÂ¸ÃÂ½ÃÂ¸ÃÂ¼ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ°Ã‘Â equity",
    lowestEquityDescription:
      "ÃÂ¡ÃÂ°ÃÂ¼ÃÂ¾ÃÂµ ÃÂ½ÃÂ¸ÃÂ·ÃÂºÃÂ¾ÃÂµ ÃÂ·ÃÂ½ÃÂ°Ã‘â€¡ÃÂµÃÂ½ÃÂ¸ÃÂµ equity Ã‘Â Ã‘Æ’Ã‘â€¡ÃÂµÃ‘â€šÃÂ¾ÃÂ¼ ÃÂ½ÃÂ°Ã‘â€¡ÃÂ°ÃÂ»Ã‘Å’ÃÂ½ÃÂ¾ÃÂ³ÃÂ¾ ÃÂ±ÃÂ°ÃÂ»ÃÂ°ÃÂ½Ã‘ÂÃÂ°.",

    positiveTrades: "ÃÅ¸ÃÂ¾ÃÂ»ÃÂ¾ÃÂ¶ÃÂ¸Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂµ Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸",
    positiveTradesDescription:
      "ÃÂ¡ÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸, ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬Ã‘â€¹Ã‘â€šÃ‘â€¹ÃÂµ Ã‘Â ÃÂ¿ÃÂ¾ÃÂ»ÃÂ¾ÃÂ¶ÃÂ¸Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂ¼ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€šÃÂ¾ÃÂ¼.",
    negativeTrades: "ÃÅ¾Ã‘â€šÃ‘â‚¬ÃÂ¸Ã‘â€ ÃÂ°Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂµ Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸",
    negativeTradesDescription:
      "ÃÂ¡ÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸, ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬Ã‘â€¹Ã‘â€šÃ‘â€¹ÃÂµ Ã‘Â ÃÂ¾Ã‘â€šÃ‘â‚¬ÃÂ¸Ã‘â€ ÃÂ°Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂ¼ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€šÃÂ¾ÃÂ¼.",
    flatTrades: "Flat Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸",
    flatTradesDescription:
      "ÃÂ¡ÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸, ÃÂ·ÃÂ°ÃÂºÃ‘â‚¬Ã‘â€¹Ã‘â€šÃ‘â€¹ÃÂµ ÃÂ² break-even ÃÂ¸ÃÂ»ÃÂ¸ ÃÂ±ÃÂµÃÂ· PnL.",
    averagePnl: "ÃÂ¡Ã‘â‚¬ÃÂµÃÂ´ÃÂ½ÃÂ¸ÃÂ¹ PnL",
    averagePnlDescription:
      "ÃÂ¡Ã‘â‚¬ÃÂµÃÂ´ÃÂ½ÃÂ¸ÃÂ¹ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ½ÃÂ° ÃÂ¾ÃÂ´ÃÂ½Ã‘Æ’ ÃÂ·ÃÂ°ÃÂ¿ÃÂ¸Ã‘ÂÃÂ°ÃÂ½ÃÂ½Ã‘Æ’Ã‘Å½ Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃ‘Æ’.",

    bestTrade: "Ãâ€ºÃ‘Æ’Ã‘â€¡Ã‘Ë†ÃÂ°Ã‘Â Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ°",
    bestTradeDescription:
      "ÃÂ¡ÃÂ°ÃÂ¼Ã‘â€¹ÃÂ¹ ÃÂºÃ‘â‚¬Ã‘Æ’ÃÂ¿ÃÂ½Ã‘â€¹ÃÂ¹ ÃÂµÃÂ´ÃÂ¸ÃÂ½ÃÂ¸Ã‘â€¡ÃÂ½Ã‘â€¹ÃÂ¹ ÃÂ¿ÃÂ¾ÃÂ»ÃÂ¾ÃÂ¶ÃÂ¸Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂ¹ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ½ÃÂ° Ã‘ÂÃ‘â€šÃÂ¾ÃÂ¼ ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂµ.",
    worstTrade: "ÃÂ¥Ã‘Æ’ÃÂ´Ã‘Ë†ÃÂ°Ã‘Â Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ°",
    worstTradeDescription:
      "ÃÂ¡ÃÂ°ÃÂ¼Ã‘â€¹ÃÂ¹ ÃÂºÃ‘â‚¬Ã‘Æ’ÃÂ¿ÃÂ½Ã‘â€¹ÃÂ¹ ÃÂµÃÂ´ÃÂ¸ÃÂ½ÃÂ¸Ã‘â€¡ÃÂ½Ã‘â€¹ÃÂ¹ ÃÂ¾Ã‘â€šÃ‘â‚¬ÃÂ¸Ã‘â€ ÃÂ°Ã‘â€šÃÂµÃÂ»Ã‘Å’ÃÂ½Ã‘â€¹ÃÂ¹ Ã‘â‚¬ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š ÃÂ½ÃÂ° Ã‘ÂÃ‘â€šÃÂ¾ÃÂ¼ ÃÂ°ÃÂºÃÂºÃÂ°Ã‘Æ’ÃÂ½Ã‘â€šÃÂµ.",

    equityHistory: "ÃËœÃ‘ÂÃ‘â€šÃÂ¾Ã‘â‚¬ÃÂ¸Ã‘Â equity",
    tradeByTradeProgression: "ÃÅ¸Ã‘â‚¬ÃÂ¾ÃÂ³Ã‘â‚¬ÃÂµÃ‘ÂÃ‘ÂÃÂ¸Ã‘Â Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ° ÃÂ·ÃÂ° Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¾ÃÂ¹",
    showingLatest: (shown, total) =>
      `ÃÅ¸ÃÂ¾ÃÂºÃÂ°ÃÂ·ÃÂ°ÃÂ½Ã‘â€¹ ÃÂ¿ÃÂ¾Ã‘ÂÃÂ»ÃÂµÃÂ´ÃÂ½ÃÂ¸ÃÂµ ${shown} ÃÂ¸ÃÂ· ${total} Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂ¾ÃÂº`,

    unknownSymbol: "ÃÂÃÂµÃÂ¸ÃÂ·ÃÂ²ÃÂµÃ‘ÂÃ‘â€šÃÂ½Ã‘â€¹ÃÂ¹ Ã‘ÂÃÂ¸ÃÂ¼ÃÂ²ÃÂ¾ÃÂ»",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Ãâ€ÃÂ°Ã‘â€šÃÂ°",
    symbol: "ÃÂ¡ÃÂ¸ÃÂ¼ÃÂ²ÃÂ¾ÃÂ»",
    outcome: "ÃÂ ÃÂµÃÂ·Ã‘Æ’ÃÂ»Ã‘Å’Ã‘â€šÃÂ°Ã‘â€š",
    pnl: "PnL",
    noEquityHistory:
      "ÃËœÃ‘ÂÃ‘â€šÃÂ¾Ã‘â‚¬ÃÂ¸ÃÂ¸ equity ÃÂ¿ÃÂ¾ÃÂºÃÂ° ÃÂ½ÃÂµÃ‘â€š. Ãâ€ÃÂ¾ÃÂ±ÃÂ°ÃÂ²Ã‘Å’ Ã‘ÂÃÂ´ÃÂµÃÂ»ÃÂºÃÂ¸, Ã‘â€¡Ã‘â€šÃÂ¾ÃÂ±Ã‘â€¹ ÃÂ½ÃÂ°Ã‘â€¡ÃÂ°Ã‘â€šÃ‘Å’ ÃÂ¾Ã‘â€šÃ‘ÂÃÂ»ÃÂµÃÂ¶ÃÂ¸ÃÂ²ÃÂ°Ã‘â€šÃ‘Å’ ÃÂ¿Ã‘â‚¬ÃÂ¾ÃÂ³Ã‘â‚¬ÃÂµÃ‘ÂÃ‘Â ÃÂºÃÂ°ÃÂ¿ÃÂ¸Ã‘â€šÃÂ°ÃÂ»ÃÂ°.",
  },

  es: {
    heroBadge: "Seguimiento de capital",
    heroEyebrow: "Centro de control de equity",
    heroTitle: "Curva Equity",
    heroDescription:
      "Sigue el crecimiento de la cuenta, la protecciÃƒÂ³n del capital, el comportamiento del drawdown y la evoluciÃƒÂ³n de tu equity en el tiempo.",
    backToAccountHub: "Volver al Account Hub",

    currentEquity: "Equity actual",
    currentEquityDescription:
      "ÃƒÅ¡ltimo valor de equity calculado despuÃƒÂ©s de las operaciones cerradas.",
    totalPnl: "PnL total",
    totalPnlDescription:
      "Ganancia o pÃƒÂ©rdida total generada por la cuenta.",
    growth: "Crecimiento",
    growthDescription:
      "Rendimiento comparado con el balance inicial.",
    maxDrawdown: "Drawdown mÃƒÂ¡ximo",
    maxDrawdownDescription:
      "Mayor retroceso de equity registrado en la cuenta.",

    accountGrowth: "Crecimiento de la cuenta",
    equityProgression: "ProgresiÃƒÂ³n de Equity",
    noTradesChart:
      "AÃƒÂºn no hay operaciones. Cuando agregues trades, la curva equity aparecerÃƒÂ¡ aquÃƒÂ­.",

    equityPeak: "Pico de Equity",
    equityPeakDescription:
      "Valor de equity mÃƒÂ¡s alto registrado en esta cuenta.",
    lowestEquity: "Equity mÃƒÂ­nima",
    lowestEquityDescription:
      "Valor de equity mÃƒÂ¡s bajo registrado incluyendo el balance inicial.",

    positiveTrades: "Trades positivos",
    positiveTradesDescription:
      "Trades cerrados con resultado positivo.",
    negativeTrades: "Trades negativos",
    negativeTradesDescription:
      "Trades cerrados con resultado negativo.",
    flatTrades: "Trades flat",
    flatTradesDescription:
      "Trades cerrados en break-even o sin PnL.",
    averagePnl: "PnL promedio",
    averagePnlDescription:
      "Resultado promedio por trade registrado.",

    bestTrade: "Mejor trade",
    bestTradeDescription:
      "Mayor resultado positivo individual registrado en esta cuenta.",
    worstTrade: "Peor trade",
    worstTradeDescription:
      "Mayor resultado negativo individual registrado en esta cuenta.",

    equityHistory: "Historial de equity",
    tradeByTradeProgression: "ProgresiÃƒÂ³n trade por trade",
    showingLatest: (shown, total) =>
      `Mostrando los ÃƒÂºltimos ${shown} de ${total} trades`,

    unknownSymbol: "SÃƒÂ­mbolo desconocido",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Fecha",
    symbol: "SÃƒÂ­mbolo",
    outcome: "Resultado",
    pnl: "PnL",
    noEquityHistory:
      "AÃƒÂºn no hay historial de equity. Agrega trades para empezar a seguir la progresiÃƒÂ³n del capital.",
  },

  fr: {
    heroBadge: "Suivi du capital",
    heroEyebrow: "Centre de contrÃƒÂ´le equity",
    heroTitle: "Courbe Equity",
    heroDescription:
      "Suis la croissance du compte, la protection du capital, le comportement du drawdown et lÃ¢â‚¬â„¢ÃƒÂ©volution de ton equity dans le temps.",
    backToAccountHub: "Retour ÃƒÂ  lÃ¢â‚¬â„¢Account Hub",

    currentEquity: "Equity actuelle",
    currentEquityDescription:
      "DerniÃƒÂ¨re equity calculÃƒÂ©e aprÃƒÂ¨s les trades clÃƒÂ´turÃƒÂ©s.",
    totalPnl: "PnL total",
    totalPnlDescription:
      "Profit ou perte total gÃƒÂ©nÃƒÂ©rÃƒÂ© par le compte.",
    growth: "Croissance",
    growthDescription:
      "Performance comparÃƒÂ©e au solde initial.",
    maxDrawdown: "Drawdown maximal",
    maxDrawdownDescription:
      "Plus forte baisse dÃ¢â‚¬â„¢equity enregistrÃƒÂ©e sur le compte.",

    accountGrowth: "Croissance du compte",
    equityProgression: "Progression Equity",
    noTradesChart:
      "Aucun trade pour le moment. Une fois les trades ajoutÃƒÂ©s, la courbe equity apparaÃƒÂ®tra ici.",

    equityPeak: "Pic Equity",
    equityPeakDescription:
      "Valeur equity la plus ÃƒÂ©levÃƒÂ©e enregistrÃƒÂ©e sur ce compte.",
    lowestEquity: "Equity minimale",
    lowestEquityDescription:
      "Valeur equity la plus basse enregistrÃƒÂ©e, solde initial inclus.",

    positiveTrades: "Trades positifs",
    positiveTradesDescription:
      "Trades clÃƒÂ´turÃƒÂ©s avec un rÃƒÂ©sultat positif.",
    negativeTrades: "Trades nÃƒÂ©gatifs",
    negativeTradesDescription:
      "Trades clÃƒÂ´turÃƒÂ©s avec un rÃƒÂ©sultat nÃƒÂ©gatif.",
    flatTrades: "Trades flat",
    flatTradesDescription:
      "Trades clÃƒÂ´turÃƒÂ©s au break-even ou sans PnL.",
    averagePnl: "PnL moyen",
    averagePnlDescription:
      "RÃƒÂ©sultat moyen par trade enregistrÃƒÂ©.",

    bestTrade: "Meilleur trade",
    bestTradeDescription:
      "Plus grand rÃƒÂ©sultat positif individuel enregistrÃƒÂ© sur ce compte.",
    worstTrade: "Pire trade",
    worstTradeDescription:
      "Plus grand rÃƒÂ©sultat nÃƒÂ©gatif individuel enregistrÃƒÂ© sur ce compte.",

    equityHistory: "Historique equity",
    tradeByTradeProgression: "Progression trade par trade",
    showingLatest: (shown, total) =>
      `Affichage des ${shown} derniers trades sur ${total}`,

    unknownSymbol: "Symbole inconnu",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Date",
    symbol: "Symbole",
    outcome: "RÃƒÂ©sultat",
    pnl: "PnL",
    noEquityHistory:
      "Aucun historique equity pour le moment. Ajoute des trades pour commencer ÃƒÂ  suivre la progression du capital.",
  },

  de: {
    heroBadge: "Kapitalverfolgung",
    heroEyebrow: "Equity-Kontrollzentrum",
    heroTitle: "Equity-Kurve",
    heroDescription:
      "Verfolge Kontowachstum, Kapitalschutz, Drawdown-Verhalten und die Entwicklung deiner Trading-Equity im Zeitverlauf.",
    backToAccountHub: "ZurÃƒÂ¼ck zum Account Hub",

    currentEquity: "Aktuelle Equity",
    currentEquityDescription:
      "Zuletzt berechnete Konto-Equity nach geschlossenen Trades.",
    totalPnl: "Gesamt-PnL",
    totalPnlDescription:
      "Gesamter Gewinn oder Verlust, der vom Konto erzeugt wurde.",
    growth: "Wachstum",
    growthDescription:
      "Performance im Vergleich zum Anfangssaldo.",
    maxDrawdown: "Maximaler Drawdown",
    maxDrawdownDescription:
      "Tiefster Equity-RÃƒÂ¼ckgang, der auf dem Konto erfasst wurde.",

    accountGrowth: "Kontowachstum",
    equityProgression: "Equity-Entwicklung",
    noTradesChart:
      "Noch keine Trades. Sobald Trades hinzugefÃƒÂ¼gt werden, erscheint die Equity-Kurve hier.",

    equityPeak: "Equity-Hoch",
    equityPeakDescription:
      "HÃƒÂ¶chster Equity-Wert, der fÃƒÂ¼r dieses Konto erfasst wurde.",
    lowestEquity: "Niedrigste Equity",
    lowestEquityDescription:
      "Niedrigster Equity-Wert inklusive Anfangssaldo.",

    positiveTrades: "Positive Trades",
    positiveTradesDescription:
      "Trades, die mit positivem Ergebnis geschlossen wurden.",
    negativeTrades: "Negative Trades",
    negativeTradesDescription:
      "Trades, die mit negativem Ergebnis geschlossen wurden.",
    flatTrades: "Flat Trades",
    flatTradesDescription:
      "Trades, die bei Break-even oder ohne PnL geschlossen wurden.",
    averagePnl: "Durchschnittlicher PnL",
    averagePnlDescription:
      "Durchschnittliches Ergebnis pro erfasstem Trade.",

    bestTrade: "Bester Trade",
    bestTradeDescription:
      "GrÃƒÂ¶ÃƒÅ¸tes einzelnes positives Ergebnis auf diesem Konto.",
    worstTrade: "Schlechtester Trade",
    worstTradeDescription:
      "GrÃƒÂ¶ÃƒÅ¸tes einzelnes negatives Ergebnis auf diesem Konto.",

    equityHistory: "Equity-Historie",
    tradeByTradeProgression: "Trade-fÃƒÂ¼r-Trade-Entwicklung",
    showingLatest: (shown, total) =>
      `Zeige die letzten ${shown} von ${total} Trades`,

    unknownSymbol: "Unbekanntes Symbol",
    equity: "Equity",
    drawdown: "Drawdown",
    date: "Datum",
    symbol: "Symbol",
    outcome: "Ergebnis",
    pnl: "PnL",
    noEquityHistory:
      "Noch keine Equity-Historie. FÃƒÂ¼ge Trades hinzu, um die Kapitalentwicklung zu verfolgen.",
  },
};

function formatPercent(
  value: number,
  language: AppLanguage
) {
  return formatPercentByLanguage(value, language);
}

function formatDate(
  date: Date,
  language: AppLanguage
) {
  return formatDateByLanguage(date, language, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

function formatShortDate(
  date: Date,
  language: AppLanguage
) {
  return formatDateByLanguage(date, language, {
    day: "2-digit",
    month: "2-digit",
  });
}

function getResultTone(value: number) {
  if (value > 0) {
    return "text-green-400";
  }

  if (value < 0) {
    return "text-red-400";
  }

  return "text-yellow-400";
}

function StatCard({
  label,
  value,
  description,
  icon: Icon,
  tone = "text-white",
}: StatCardProps) {
  return (
    <div className="card-hover rounded-3xl border border-white/10 bg-white/[0.03] p-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-sm text-gray-400">
            {label}
          </p>

          <h2 className={`mt-3 text-3xl font-black ${tone}`}>
            {value}
          </h2>
        </div>

        <div className="rounded-2xl border border-white/10 bg-black/20 p-3 text-accent-bright">
          <Icon size={20} />
        </div>
      </div>

      <p className="mt-4 text-sm leading-6 text-gray-500">
        {description}
      </p>
    </div>
  );
}

export default async function EquityPage({
  params,
}: {
  params: Promise<{ accountId: string }>;
}) {
  const session = await auth();

  if (!session?.user?.id) {
    redirect("/login");
  }

  const { accountId } = await params;

  const membership = await prisma.accountMember.findFirst({
    where: {
      userId: session.user.id,
      tradingAccountId: accountId,
    },

    include: {
      tradingAccount: true,
    },
  });

  if (!membership) {
    redirect("/accounts");
  }

  await prisma.user.update({
    where: {
      id: session.user.id,
    },
    data: {
      lastSeenAt: new Date(),
      lastActivityAt: new Date(),
    },
  });

  const currentUser = await prisma.user.findUnique({
    where: {
      id: session.user.id,
    },
    select: {
      appLanguage: true,
    },
  });

  const language = normalizeAppLanguage(
    currentUser?.appLanguage
  );

  const t = equityLabels[language];

  const account = membership.tradingAccount;

  const trades = await prisma.trade.findMany({
    where: {
      tradingAccountId: accountId,
    },

    orderBy: [
      {
        openDate: "asc",
      },
      {
        id: "asc",
      },
    ],
  });

  const initialBalance = account.initialBalance || 0;
  const currency = account.currency || "USD";

  const money = (value: number) =>
    formatCurrencyByLanguage(
      value,
      currency,
      language
    );

  const currentEquity =
    trades.length > 0
      ? trades[trades.length - 1].equity || initialBalance
      : initialBalance;

  const totalPnl = trades.reduce(
    (acc, trade) => acc + (trade.resultUsd || 0),
    0
  );

  const currentProfitPercent =
    initialBalance > 0
      ? ((currentEquity - initialBalance) /
        initialBalance) *
      100
      : 0;

  const positiveTrades = trades.filter(
    (trade) => (trade.resultUsd || 0) > 0
  ).length;

  const negativeTrades = trades.filter(
    (trade) => (trade.resultUsd || 0) < 0
  ).length;

  const flatTrades = trades.filter(
    (trade) => (trade.resultUsd || 0) === 0
  ).length;

  const maxDrawdown =
    trades.length > 0
      ? Math.min(
        ...trades.map(
          (trade) => trade.drawdownPercent || 0
        )
      )
      : 0;

  const maxEquity =
    trades.length > 0
      ? Math.max(
        initialBalance,
        ...trades.map(
          (trade) => trade.equity || initialBalance
        )
      )
      : initialBalance;

  const lowestEquity =
    trades.length > 0
      ? Math.min(
        initialBalance,
        ...trades.map(
          (trade) => trade.equity || initialBalance
        )
      )
      : initialBalance;

  const bestTrade =
    trades.length > 0
      ? Math.max(
        ...trades.map((trade) => trade.resultUsd || 0)
      )
      : 0;

  const worstTrade =
    trades.length > 0
      ? Math.min(
        ...trades.map((trade) => trade.resultUsd || 0)
      )
      : 0;

  const averagePnl =
    trades.length > 0 ? totalPnl / trades.length : 0;

  const chartData = trades.map((trade) => ({
    date: formatShortDate(trade.openDate, language),
    equity: trade.equity || initialBalance,
  }));

  const recentTrades = [...trades].reverse().slice(0, 10);

  const stats = [
    {
      label: t.currentEquity,
      value: money(currentEquity),
      description: t.currentEquityDescription,
      icon: Wallet,
      tone: "text-white",
    },
    {
      label: t.totalPnl,
      value: money(totalPnl),
      description: t.totalPnlDescription,
      icon: TrendingUp,
      tone: getResultTone(totalPnl),
    },
    {
      label: t.growth,
      value: formatPercent(
        currentProfitPercent,
        language
      ),
      description: t.growthDescription,
      icon: BarChart3,
      tone: getResultTone(currentProfitPercent),
    },
    {
      label: t.maxDrawdown,
      value: formatPercent(maxDrawdown, language),
      description: t.maxDrawdownDescription,
      icon: ShieldAlert,
      tone:
        maxDrawdown < 0
          ? "text-red-400"
          : "text-yellow-400",
    },
  ];

  return (
    <div className="space-y-12">
      <section className="relative overflow-hidden rounded-[32px] border border-white/10 bg-white/[0.03] p-8 sm:p-10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,color-mix(in_srgb,var(--color-accent-bright)_14%,transparent),transparent_35%),radial-gradient(circle_at_bottom_left,rgba(168,85,247,0.08),transparent_35%)]" />

        <div className="relative z-10 flex flex-col gap-8 xl:flex-row xl:items-end xl:justify-between">
          <div>
            <div className="mb-6 flex flex-wrap items-center gap-3">
              <span className="rounded-full border border-accent-bright/20 bg-accent-bright/10 px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-accent-bright">
                {t.heroBadge}
              </span>

              <span className="rounded-full border border-white/10 bg-black/20 px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-gray-300">
                {account.name}
              </span>
            </div>

            <p className="text-sm text-gray-400">
              {t.heroEyebrow}
            </p>

            <h1 className="mt-3 text-5xl font-black tracking-tight text-white sm:text-6xl">
              {t.heroTitle}
            </h1>

            <p className="mt-6 max-w-3xl text-base leading-7 text-gray-400">
              {t.heroDescription}
            </p>
          </div>

          <Link
            href={`/accounts/${accountId}`}
            className="flex w-fit items-center gap-2 rounded-2xl border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white transition hover:bg-white/[0.08]"
          >
            <ArrowLeft size={17} />
            {t.backToAccountHub}
          </Link>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        {stats.map((stat) => (
          <StatCard
            key={stat.label}
            label={stat.label}
            value={stat.value}
            description={stat.description}
            icon={stat.icon}
            tone={stat.tone}
          />
        ))}
      </section>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className="card-hover rounded-3xl border border-white/10 bg-white/[0.03] p-6 xl:col-span-2">
          <div className="mb-6 flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-gray-400">
                {t.accountGrowth}
              </p>

              <h2 className="mt-1 text-2xl font-black text-white">
                {t.equityProgression}
              </h2>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-3 text-accent-bright">
              <LineChartIcon size={20} />
            </div>
          </div>

          {chartData.length > 0 ? (
            <div className="min-w-0">
              <EquityChart data={chartData} language={language} />
            </div>
          ) : (
            <div className="flex min-h-[280px] items-center justify-center rounded-2xl border border-dashed border-white/10 bg-black/20 p-8 text-center text-sm leading-6 text-gray-400">
              {t.noTradesChart}
            </div>
          )}
        </div>

        <div className="grid gap-4">
          <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
            <p className="text-sm text-gray-400">
              {t.equityPeak}
            </p>

            <h2 className="mt-3 text-3xl font-black text-accent">
              {money(maxEquity)}
            </h2>

            <p className="mt-4 text-sm leading-6 text-gray-500">
              {t.equityPeakDescription}
            </p>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
            <p className="text-sm text-gray-400">
              {t.lowestEquity}
            </p>

            <h2 className="mt-3 text-3xl font-black text-red-400">
              {money(lowestEquity)}
            </h2>

            <p className="mt-4 text-sm leading-6 text-gray-500">
              {t.lowestEquityDescription}
            </p>
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label={t.positiveTrades}
          value={positiveTrades}
          description={t.positiveTradesDescription}
          icon={TrendingUp}
          tone="text-accent"
        />

        <StatCard
          label={t.negativeTrades}
          value={negativeTrades}
          description={t.negativeTradesDescription}
          icon={TrendingDown}
          tone="text-red-400"
        />

        <StatCard
          label={t.flatTrades}
          value={flatTrades}
          description={t.flatTradesDescription}
          icon={Activity}
          tone="text-yellow-400"
        />

        <StatCard
          label={t.averagePnl}
          value={money(averagePnl)}
          description={t.averagePnlDescription}
          icon={BarChart3}
          tone={getResultTone(averagePnl)}
        />
      </section>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
          <p className="text-sm text-gray-400">
            {t.bestTrade}
          </p>

          <h2 className="mt-3 text-4xl font-black text-accent">
            {money(bestTrade)}
          </h2>

          <p className="mt-4 text-sm leading-6 text-gray-500">
            {t.bestTradeDescription}
          </p>
        </div>

        <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
          <p className="text-sm text-gray-400">
            {t.worstTrade}
          </p>

          <h2 className="mt-3 text-4xl font-black text-red-400">
            {money(worstTrade)}
          </h2>

          <p className="mt-4 text-sm leading-6 text-gray-500">
            {t.worstTradeDescription}
          </p>
        </div>
      </section>

      <section className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
        <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-sm text-gray-400">
              {t.equityHistory}
            </p>

            <h2 className="mt-1 text-2xl font-black text-white">
              {t.tradeByTradeProgression}
            </h2>
          </div>

          <p className="text-sm text-gray-500">
            {t.showingLatest(
              recentTrades.length,
              trades.length
            )}
          </p>
        </div>

        {recentTrades.length > 0 ? (
          <>
            <div className="space-y-3 lg:hidden">
              {recentTrades.map((trade) => {
                const result = trade.resultUsd || 0;
                const equity =
                  trade.equity || initialBalance;
                const drawdown =
                  trade.drawdownPercent || 0;

                return (
                  <div
                    key={trade.id}
                    className="rounded-2xl border border-white/10 bg-black/20 p-4"
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="min-w-0">
                        <p className="truncate font-bold text-white">
                          {trade.symbol || t.unknownSymbol}
                        </p>

                        <p className="mt-1 text-xs text-gray-500">
                          {formatDate(
                            trade.openDate,
                            language
                          )}{" "}
                          Ã‚Â· {trade.outcome || "-"}
                        </p>
                      </div>

                      <p
                        className={`shrink-0 font-black ${getResultTone(
                          result
                        )}`}
                      >
                        {money(result)}
                      </p>
                    </div>

                    <div className="mt-4 grid grid-cols-2 gap-3 text-sm">
                      <div className="rounded-xl bg-white/[0.03] p-3">
                        <p className="text-gray-500">
                          {t.equity}
                        </p>
                        <p className="mt-1 font-bold text-white">
                          {money(equity)}
                        </p>
                      </div>

                      <div className="rounded-xl bg-white/[0.03] p-3">
                        <p className="text-gray-500">
                          {t.drawdown}
                        </p>
                        <p
                          className={`mt-1 font-bold ${drawdown < 0
                              ? "text-red-400"
                              : "text-gray-300"
                            }`}
                        >
                          {formatPercent(
                            drawdown,
                            language
                          )}
                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            <div className="hidden overflow-x-auto rounded-2xl border border-white/10 lg:block">
              <table className="w-full border-collapse">
                <thead className="bg-white/5 text-left text-sm text-gray-400">
                  <tr>
                    <th className="p-4">
                      {t.date}
                    </th>
                    <th className="p-4">
                      {t.symbol}
                    </th>
                    <th className="p-4">
                      {t.outcome}
                    </th>
                    <th className="p-4">
                      {t.equity}
                    </th>
                    <th className="p-4">
                      {t.pnl}
                    </th>
                    <th className="p-4">
                      {t.drawdown}
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {recentTrades.map((trade) => {
                    const result =
                      trade.resultUsd || 0;
                    const drawdown =
                      trade.drawdownPercent || 0;

                    return (
                      <tr
                        key={trade.id}
                        className="border-t border-white/10"
                      >
                        <td className="p-4 text-gray-300">
                          {formatDate(
                            trade.openDate,
                            language
                          )}
                        </td>

                        <td className="p-4 font-semibold text-white">
                          {trade.symbol || "-"}
                        </td>

                        <td className="p-4 text-gray-300">
                          {trade.outcome || "-"}
                        </td>

                        <td className="p-4 font-semibold text-white">
                          {money(
                            trade.equity ||
                            initialBalance
                          )}
                        </td>

                        <td
                          className={`p-4 font-semibold ${getResultTone(
                            result
                          )}`}
                        >
                          {money(result)}
                        </td>

                        <td
                          className={`p-4 font-semibold ${drawdown < 0
                              ? "text-red-400"
                              : "text-gray-300"
                            }`}
                        >
                          {formatPercent(
                            drawdown,
                            language
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </>
        ) : (
          <div className="rounded-2xl border border-dashed border-white/10 bg-black/20 p-8 text-center text-sm text-gray-400">
            {t.noEquityHistory}
          </div>
        )}
      </section>
    </div>
  );
}
