export default function PDFReportFooter() {
  return (
    <div className="hidden print:hidden report-card mt-10 rounded-[28px] border border-white/10 bg-black/30 p-6 text-center backdrop-blur-xl">
      <p className="text-xs uppercase tracking-[0.25em] text-cyan-400">
        VOLTIS Intelligence System
      </p>

      <p className="mt-3 text-sm text-gray-400">
        Generated by VOLTIS · Trading Performance Operating System
      </p>
    </div>
  );
}