-- CreateTable
CREATE TABLE "Trade" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "openDate" DATETIME NOT NULL,
    "openTime" TEXT,
    "reason" TEXT,
    "strategy" TEXT,
    "symbol" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "amount" REAL,
    "openingPrice" REAL,
    "stopLoss" REAL,
    "takeProfit" REAL,
    "riskReward" REAL,
    "closeDate" DATETIME,
    "closingPrice" REAL,
    "outcome" TEXT,
    "resultUsd" REAL,
    "resultPercent" REAL,
    "equity" REAL,
    "equityPeak" REAL,
    "drawdownPercent" REAL,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
